### ISSUE TITLE
Chapter 2: Describing Performance [Proposal to consider Uptime/availability as another key metric]

### ISSUE THREAD

**Issue by mpalriwal-Netflix** [ept/ddia2-feedback#15]
[BookLink](https://learning.oreilly.com/library/view/designing-data-intensive-applications/9781098119058/ch02.html#:-:text=The%20unit%20of%20measurement%20is%20seconds.) 

Two feedback 
------------------
1) 
> Chapter 2 primarily focuses on response time and throughput, but service uptime and availability are also crucial metrics for service owners when defining SLOs/SLAs, such as 99% uptime or 99.9% availability. 

``Throughput`` is used to measure ``Scalability``.
``Latency`` is used to measure ``Responsiveness``.
``Uptime`` is used to measure ``Availability``.

For a more detailed explanation of uptime, you can refer to the well-known Google paper linked below:
https://www.usenix.org/system/files/nsdi20spring_hauer_prepub.pdf

Below chart provides a breakdown of how to achieve 99.99% we are only allowed to have ~52 min or less of downtime in a year, though the definition of downtime can be adjusted depending on service tier. 

<img width="638" alt="Screenshot 2024-10-10 at 12 54 38 AM" src="https://github.com/user-attachments/assets/c4f8fe58-6feb-4a92-be7d-00a519b5393d">

- - - 
2) 
> For response time, you mentioned the unit of measurement is second, it's more accurate to refer to it as a ``duration``. As it can be measured in various units such as seconds, milliseconds, or even microseconds, depending on the context and precision required.

https://learning.oreilly.com/library/view/designing-data-intensive-applications/9781098119058/ch02.html#:-:text=The%20unit%20of%20measurement%20is%20seconds.

**Comment by ept** [comment]
* We already make the point (in the section "Describing Load") that throughput is one measure of load for the purpose of scalability. But I think framing it as the only measure of scalability would be too restrictive; scalability may also concern dataset size, or level of concurrency, or other things that are not measured by throughput.
* I'm a bit wary of uptime, since it's hard to define well, as the Google paper aptly demonstrates. For example, if a service exceeds the response time specified in the SLO, but otherwise returns valid responses, is it up or not? If half of a service's responses are good and the other half are errors, is the service up or not? As there is no binary distinction between "up" and "down", I think it is much simpler to define SLOs in terms of percentages of responses, not in terms of time.
* I prefer to say that the unit of measurement is "seconds" since "duration" is a bit more abstract and harder to understand – especially when contrasted with throughput being measured in "somethings per second" (technically that should be "units of resource per unit time", but that's also more abstract and harder to understand than "somethings per second"). Also, the SI unit for duration is "seconds". I think it's clear that a microsecond is just a millionth of a second, but I can add a parenthetical remark that milliseconds or microseconds are also included in the unit of seconds.

**Comment by mpalriwal-Netflix** [comment]
Thank you for your insights. 

1. **Scalability**: I agree that throughput is just one aspect of scalability. As a ref, ICPE ‘21 [paper](https://research.spec.org/icpe_proceedings/2021/companion/p85.pdf ) define scalability beyond just throughput. 
-----
2. **Uptime**: Defining ``"UP" or "DOWN"`` can indeed be complex, but the percentage of time its ``UP``  will measure its Uptime %.  A definition of ``DOWN``  could just mean a degraded performance. 
Let's say 
     *  A tier-1 service will define ``UP``  if API Success Rate (2xx/TotalRequest) >= 99%.  (If response are delayed/timedout it will report as 4xx/5xx)
     * A non tier-1 service will define ``UP``  if API Success Rate >= 95%.  

  While the uptime % definition remains same for all. 

----
3. **Response Time Measurement**: Agree with your reasoning to keep SI unit of duration, with more [fast responsive system, the micro/millis level measurement are becoming norm.](https://devblogs.microsoft.com/oldnewthing/20240206-00/?p=109365) 


---

Thank you for considering my suggestions.

**Comment by ept** [comment]
I've updated the unit of time measurement; with regard to the other points, I'm inclined to keep things as they are currently, because I think the text already captures the key nuances without getting too much into the weeds. @criccomini what do you think?

**Comment by mpalriwal-Netflix** [comment]
Thanks @ept for updating the time measurement. I understand your point about the nuances. Happy to discuss further if needed. Looking forward to @criccomini thoughts!

**Comment by criccomini** [comment]
Closing the loop on this. Pretty much agree with Martin's initial comments. :)

**Comment by mpalriwal-Netflix** [comment]
Thank you for considering the proposal and for sharing your honest thoughts.
