### ISSUE TITLE
Topic suggestions for the second version (Security, Privacy, Compliance, Hardware accelerators)

### ISSUE THREAD

**Issue by xuancanh** [ept/ddia2-feedback#5]
Will there be a chapter on Security, Privacy, and Compliance? While they may not be unique problems to data-intensive systems, they are important non-functional requirements that will come up when designing and building real-world systems. Issues to discuss may include data residency, security and isolation in multitenant systems, and privacy (data masking, anonymization, etc..) in batch/streaming data analytic and machine learning systems, etc...

Another interesting topics is hardware accelerators. They are widely used in modern data-intensive systems, especially in machine learning (GPU, TPU) or data analytics (Redshift Aqua). It was also mentioned in this paper https://arxiv.org/pdf/2203.10836, but only briefly.

**Comment by ept** [comment]
Hi @xuancanh, thanks for your note. In the first edition the final section is on law and ethics, and we're thinking of expanding that in the second edition. It's tricky though, because there doesn't seem to be general agreement on what technical measures are actually necessary or sufficient in order to comply with regulations such as GDPR. We probably won't go deep into privacy techniques, as that's a big topic that's already covered in other books, and a bit too far removed from the core topics of the book.

On hardware accelerators, my sense is that they're important for machine learning, but that's also mostly outside of the scope of this book, which is more database-oriented. Within the area of databases I've seen some research on using special hardware, but I get the sense that it isn't particularly mainstream yet, and hasn't yet had a big impact on data systems architecture. If I'm mistaken, I'd appreciate any resources you can send us.

**Comment by xuancanh** [comment]
Hi @ept, thank you for your response.

I think the reason for hardware accelerators not becoming mainstream is that there are only a few companies that have the resources to pursue that direction, and it is tightly coupled with the cloud provider that develops that technology. I agree that overall it doesn't have a big impact on data systems architecture, it is more about optimizing certain parts of the existing architecture. While a dedicated chapter for it may be unnecessary, some mentions about it could be helpful for readers to explore later. There are some production database management systems that I'm aware of using hardware accelerators, such as [Redshift Aqua](https://aws.amazon.com/blogs/aws/new-aqua-advanced-query-accelerator-for-amazon-redshift/), [Alibaba X-DB](https://www.alibabacloud.com/blog/when-databases-meet-fpga-achieving-1-million-tps-with-x-db-heterogeneous-computing_594147), [Alibaba PolarDB](https://www.alibabacloud.com/help/en/polardb/polardb-for-oracle/enable-gpu-accelerated-computing), and [SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/integrated-acceleration/overview?view=sql-server-ver16).

Regarding movements that have a big impact on data systems architecture, I think the shared-something (log/storage/memory) architecture (or disaggregated architecture) is gaining a lot of momentum recently with AWS Aurora, Facebook Delos, Alibaba PolarDB. The shared-log architecture is widely used internally at AWS, as mentioned [here](https://brooker.co.za/blog/2024/04/25/memorydb.html) by Marc Brooker (the journal service). Alibaba is also pursuing the shared-something approach with PolarDB, with [PolarDB-MP](https://www.alibabacloud.com/blog/601453) and PolarDB-SCC. 

Thank you so much for writing the book!
